[project]
title = "Action"
version = "0.0.0"

[api]
source = "src/modules"
entrypoint = "OtherModule"

[docusaurus]
tagline = "Making multi-platform simpler"

[home]
enabled = true
includeReadme = true